my-config:
  hdfsURL: hdfs://hadoop01:9000/yunpan/
  hostURL: D:\kkFileView-4.4\file\
  temp: D:\HDFSFile\
  log: D:\log\
  hadoopJmxServerUrl : "http://192.168.164.110:50070"
  code : "UlZBVk9PRElSRkhMUkZFUQ=="
  smtp: "smtp.163.com"
  hostEmail : "yandancm@163.com"
  userName: "墨家云盘"
#  hostURL: /home/hdfsuser/
spring:
  aop:
    auto: true
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://hadoop01:3306/test?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password: daian0401
  resources:
    static-locations: classpath:/
  servlet:
    multipart:
      max-file-size: -1
      max-request-size: -1
#logging:
#  level:
#    com.yandan.yunstorage.dao : debug

server:
  port: 10001
